---
- hosts: master
  gather_facts: false
  become: true
  remote_user: ubuntu

  tasks:
    - ping:

    - name: Install other tools for master 
      ansible.builtin.shell:
        cmd: expect /home/ubuntu/expect_script_master.exp 2

