---
- hosts: nginx
  gather_facts: false
  become: true
  remote_user: ubuntu

  tasks:
    - ping:

    - name: Copy execute file for Jenkins host
      ansible.builtin.copy:
        src: ../storage/expect_script_jenkins.exp
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: '777'

    - name: Permission for master file
      ansible.builtin.shell:
        cmd: chmod +x ./install_Jenkins.sh

    - name: Install other tools for Jenkins and Nginx
      ansible.builtin.shell:
        cmd: expect /home/ubuntu/expect_script_jenkins.exp 
