---
- hosts: master
  gather_facts: false
  become: true
  remote_user: ubuntu

  vars:
    - project_path: /home/ubuntu/Devops-Project/Helm/

  vars_files:
    - ./vars/create-time-private-ip.yml

  tasks:
    - ping:

    - name: Remove old package
      ansible.builtin.shell:
        cmd: rm -f mysql-0.1.0.tgz
        chdir: "{{ project_path }}"

    - name: Remove helm installed
      ansible.builtin.shell:
        cmd: helm uninstall mysql -n dev
        chdir: "{{ project_path }}"

    - name: Package helm for mysql server
      ansible.builtin.shell:
        cmd: helm package mysql/
        chdir: "{{ project_path }}"

    - name: Using helm for installing mysql server
      ansible.builtin.shell:
        cmd: "helm install mysql mysql-0.1.0.tgz -n dev"
        chdir: "{{ project_path }}"

    - name: Set up IP for true
      ansible.builtin.command: ansible-playbook -i hosts app-configure.yaml -u ubuntu
      delegate_to: localhost

    - name: Remove old django package
      ansible.builtin.shell:
        cmd: rm -f django-0.1.0.tgz
        chdir: "{{ project_path }}"
    
    - name: Remove helm installed for django
      ansible.builtin.shell:
        cmd: helm uninstall django -n dev || true
        chdir: "{{ project_path }}"

    - name: Package helm for django application
      ansible.builtin.shell:
        cmd: helm package django/
        chdir: "{{ project_path }}"

    - name: Using helm for installing django application
      ansible.builtin.shell:
        cmd: "helm install django django-0.1.0.tgz -n dev"
        chdir: "{{ project_path }}"


