---
- hosts: master
  gather_facts: false
  become: true
  remote_user: ubuntu

  vars_files:
    - ./vars/create-time-private-ip.yml

  tasks:
    - ping:
    
    - name: Reach IP of pod that is running MYSQL server
      ansible.builtin.shell:
       cmd: "kubectl get pods -n dev -o wide | grep '^mysql' | awk '{print $6}'"
      register: mysql_pod_ip 

    - name: Change IP of database in configuration file
      ansible.builtin.lineinfile:
        path: /home/ubuntu/Devops-Project/Helm/django/values.yaml
        regexp: 'db_host: ".*"'
        line: '  db_host: "{{ mysql_pod_ip.stdout }}"'
