---
# Using temporary for nginx
- hosts: nginx
  gather_facts: false
  become: true
  remote_user: ubuntu
  
  vars:
   - dns_name: www.trourest186.online
   - key_folder: /etc/letsencrypt/live/www.trourest186.online

  vars_files:
    - ./vars/create-time-private-ip.yml

  tasks:
    - ping:

    - name: Intall Let's Encrypt for domain
      ansible.builtin.apt:
        name: letsencrypt
        state: present

    - name: Create certificate for domain
      ansible.builtin.shell: |
        set timeout 180

        spawn sudo certbot certonly --standalone --agree-tos  --preferred-challenges http -d {{ dns_name }} -v

        expect {
          "Enter" {
             send "tgpham26@gmail.com\n"
             exp_continue
          }
          "(Y)es" {
            send "Y\n"
            exp_continue
          }
          "Select the appropriate number" {
            send "1\n"
            exp_continue
          }
          timeout {
            send_user "Unexpected output\n"
            exit 1
          }
        }
        
        interact 

        exit 0
      args:
        executable: /usr/bin/expect
      delegate_to: '{{worker1}}'

    - name: Copy key.pem into Nginx
      ansible.builtin.copy:
        src: ./ec2-test-key.pem
        dest: '{{key_folder}}/ec2-test-key.pem'
        owner: ubuntu
        group: ubuntu
        mode: '0777'
        backup: yes

    - name: Copy key.sh into Nginx
      ansible.builtin.copy:
        src: ./storage/key.sh
        dest: '/home/ubuntu/key.sh'
        owner: ubuntu
        group: ubuntu
        mode: '0777'
        backup: yes

    - name: Copy execute file for Nginx host
      ansible.builtin.copy:
        src: ./storage/expect_script_key.exp
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: '0777'

    - name: Execute expect script
      ansible.builtin.shell:
        cmd: expect /home/ubuntu/expect_script_key.exp '{{master}}'
